name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]  # Adjust as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Start json-server
        run: |
          npm install -g json-server
          json-server --watch ./src/data/db.json --routes ./src/data/routes.json --port 8080 &

      - name: Wait for json-server to start
        run: |
          npm install -g wait-on
          wait-on http://localhost:8080

      - name: Verify port accessibility
        run: |
          nc -zv localhost 8080

      - name: Run tests
        run: npm test

      - name: Format code
        run: npm run format

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
